version: "3.8"
name: llana
volumes:
  llana_data:

x-shared: &shared
  restart: always
  image: juicyllama/llana:${SOFTWARE_VERSION_TAG}
  environment:
    DATABASE_URI: ${DATABASE_URI}
    JWT_KEY: ${JWT_KEY}
    DEFAULT_LIMIT: ${DEFAULT_LIMIT}
    DEFAULT_RELATIONS_LIMIT: ${DEFAULT_RELATIONS_LIMIT}
    SOFT_DELETE: ${SOFT_DELETE}
    SOFT_DELETE_KEY: ${SOFT_DELETE_KEY}
    LOG_LEVELS_PROD: ${LOG_LEVELS_PROD}
    LOG_LEVELS_SANDBOX: ${LOG_LEVELS_SANDBOX}
    LOG_LEVELS_TEST: ${LOG_LEVELS_TEST}
    LOG_LEVELS_DEV: ${LOG_LEVELS_DEV}
  volumes:
    - ./llana:/usr/src/app

  llana:
    <<: *shared
    dns:
      - 8.8.8.8    
    ports:
      - 172.17.0.1:3000:3000