name: llana

services:
    llana-test-prod-build-app:
        container_name: llana-test-prod-build-app
        build:
            context: .
            dockerfile: docker/images/base/Dockerfile
        ports:
            - "3000:3000"
        environment:
            DATABASE_URI: ${DATABASE_URI}
            JWT_KEY: ${JWT_KEY}
            HOSTS: ${HOSTS}
            SOFT_DELETE_COLUMN: ${SOFT_DELETE_COLUMN}
            LOG_LEVELS_PROD: ${LOG_LEVELS_PROD}
            AUTH_USER_TABLE_NAME: ${AUTH_USER_TABLE_NAME}
            AUTH_USER_TABLE_USERNAME_FIELD: ${AUTH_USER_TABLE_USERNAME_FIELD}
            AUTH_USER_TABLE_PASSWORD_FIELD: ${AUTH_USER_TABLE_PASSWORD_FIELD}
            AUTH_USER_TABLE_PASSWORD_ENCRYPTION: ${AUTH_USER_TABLE_PASSWORD_ENCRYPTION}
            AUTH_USER_API_KEY_LOCATION: ${AUTH_USER_API_KEY_LOCATION}
            AUTH_USER_API_KEY_NAME: ${AUTH_USER_API_KEY_NAME}
            AUTH_USER_API_KEY_FIELD: ${AUTH_USER_API_KEY_FIELD}
            ROLE_LOCATION_USER_TABLE_NAME: ${ROLE_LOCATION_USER_TABLE_NAME}
            ROLE_LOCATION_USER_TABLE_ROLE_FIELD: ${ROLE_LOCATION_USER_TABLE_ROLE_FIELD}