name: llana

networks:
    llana-network:
        driver: bridge
        name: llana-network

volumes:
    llana-mysql-data:
        name: llana-mysql-data
        driver: local
    llana-postgres-data:
        name: llana-postgres-data
        driver: local
    llana-mongodb-data:
        name: llana-mongodb-data
        driver: local

services:

    llana-mysql:
        image: mysql:8.0
        restart: always
        container_name: llana-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_DATABASE: llana
            MYSQL_ROOT_HOST: '%'
        command: --init-file /mysql/init.sql
        volumes:
            - llana-mysql-data:/var/lib/mysql
            - ./demo/databases/mysql.sql:/mysql/init.sql
        networks:
            - llana-network

    llana-postgres:
        image: postgres
        restart: always
        container_name: llana-postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: llana
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            ALLOW_IP_RANGE: '0.0.0.0/0'
        volumes:
            - llana-postgres-data:/var/lib/postgresql/data/
            - ./demo/databases/postgres.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - llana-network
    
    llana-mongodb:
        image: mongo
        restart: always
        container_name: llana-mongodb
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: pass
            MONGO_INITDB_DATABASE: llana
        volumes:
            - llana-mongodb-data:/data/db
            - ./demo/databases/mongodb.js:/docker-entrypoint-initdb.d/seed.js
        networks:
            - llana-network