name: llana

networks:
    llana-network:
        driver: bridge
        name: llana-network

volumes:
    llana-mysql-data:
        name: llana-mysql-data
        driver: local
    llana-postgres-data:
        name: llana-postgres-data
        driver: local

services:

    llana-mysql:
        image: mysql:8.0
        restart: always
        container_name: llana-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: llana
            MYSQL_ROOT_HOST: '%'
        command: --init-file /mysql/init.sql
        volumes:
            - llana-mysql-data:/var/lib/mysql
            - ./demo/databases/mysql.sql:/mysql/init.sql
        networks:
            - llana-network

    llana-postgres:
        image: postgres
        restart: always
        container_name: llana-postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=llana
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - ALLOW_IP_RANGE='0.0.0.0/0'
        volumes:
            - llana-postgres-data:/var/lib/postgresql/data/
            - ./demo/databases/postgres.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - llana-network