#
# GitHub Actions workflow.
#
# Perfoms the following actions on a pull request:
# * Checkout the code
# * Install Node.js
# * Prepare the environment
# * Install dependencies
# * Lint the code
# * Run the tests
# * Confirm the build runs
#

name: 'PR Checks: Llana'

on:
    pull_request:
        branches:
            - main
    workflow_dispatch:
    workflow_call:

jobs:
    pr_checks:
        name: 'Pull Request Package: Llana'
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: pass
                    MYSQL_DATABASE: llana
                    MYSQL_ROOT_HOST: "%"
                ports:
                    - '3307:3306'
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
        steps:

            -   name: 'Checkout'
                uses: actions/checkout@v4
                with:
                    token: ${{ secrets.GH_CI_CD_RELEASE }}

            -   name: Install Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: 18.18.2

            -   name: Prepare
                run: echo -e "shamefully-hoist=true\\n@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_AUTH_TOKEN }}" > .npmrc

            -   name: Install dependencies
                run: npm install

            -   name: Lint
                run: npm run lint

            -   name: Start mysql
                run: sudo /etc/init.d/mysql start

            -   name: Seed database
                run:  mysql -u root -p pass -h 127.0.0.1 --port 3307 < .docker/databases/mysql.sql

            -   name: Test
                run:  export DATABASE_URI="mysql://root:pass@127.0.0.1:3307/llana" && npm run test
