#
# GitHub Actions workflow.
#
# Releases the package to npm when a push into main is detected.
# * Checkout the code
# * Install Node.js
# * Install dependencies
# * Pull the latest changes
# * Bump version number
# * Release to NPM
#

name: 'Release Package: Llana'

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:

    release:
        name: 'Release Package: CLI'
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:

            -   name: 'Checkout'
                uses: actions/checkout@v4
                with:
                    token: ${{ secrets.GH_CI_CD_RELEASE }}

            -   name: 'Install Node.js'
                uses: actions/setup-node@v4
                with:
                    node-version: 18.18.2

            -   name: 'Install dependencies'
                run: npm install

            -   run: git pull --force

            -   name: 'Version Bump'
                uses: phips28/gh-action-bump-version@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GH_CI_CD_RELEASE }}
                with:
                    major-wording: 'JLMAJOR'
                    minor-wording: 'feature,feat'
                    patch-wording: 'patch,fixes,fix,misc,docs,refactor'    # Providing patch-wording will override commits
                    commit-message: 'CI: Bump Version to {{version}} [skip ci]'

            -   name: 'Authenticate with NPM'
                run: echo -e "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

            -   name: 'Publishing package'
                run: npm publish --no-git-checks --access public

            -   name: 'Docker Build'
                run: npm run docker:build

            -  name: 'Docker Push'
                run: npm run docker:push